services:
  web-dev:
    build:
      context: ./
      target: dev
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ./src/public:/usr/src/app/public
      - ./src/app.js:/usr/src/app/app.js
    ports:
      - "3011:8080"
    # https://blog.logrocket.com/node-js-docker-improve-dx-docker-compose/
