services:
  web-dev:
    build:
      context: ./
      target: ${TARGET}
      args:
        DOCKER_BUILDKIT: 1
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./src:/app/src
      - ./app.js:/app/app.js
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    ports:
      - "${PUBLISHED_PORT}:${TARGET_PORT}"

    # https://blog.logrocket.com/node-js-docker-improve-dx-docker-compose/
